### ISSUE TITLE
Any plan of releasing training code? 

### ISSUE THREAD

**Issue by i-amgeek** [prs-eth/Marigold#1]
Thank you for the great work. 

I am planning to train this model on depth images from different domains and also try training on other problem statements like semantic segmentation. 

So, it would be very helpful if you release training code as well.

**Comment by scene-the-ella** [comment]
Me too! Thanks!

**Comment by MavenDE** [comment]
That would be awesome.

**Comment by kabouzeid** [comment]
@markkua @toshas @nandometzger, could you please provide a status update on whether you plan to release the training code? If not, it's okay if you don't want to provide a reason, I'm just curious if it's in the plans at all.

**Comment by kime541200** [comment]
This is really a fantastic project, thank you for your effort! On the other hand, I'm also curious to know if you will provide methods for training or fine-tuning this model?

**Comment by markkua** [comment]
Thanks for your interest in our work. We do have a plan to release training and evaluation code in the future. However, the schedule is not clear for us yet. Please stay tuned for future updates.

**Comment by 838959823** [comment]
Now that the paper is accepted by CVPR2024. looking forward to the training code！

**Comment by somebody-chen** [comment]
Looking forward to the training code!

**Comment by scarbain** [comment]
Same ! An approximative schedule would be much appreciated :)

**Comment by LiNO3Dy** [comment]
Same

**Comment by markkua** [comment]
I've started refactoring and cleaning the code (in my part-time 💪) and will release it as soon as it's ready and tested.

**Comment by zeron21** [comment]
I can't imagine how excited I would be if I saw the training code you released. I look forward to seeing your training code released soon

**Comment by quanqhow** [comment]
Really very looking forward to the training code! Thank you very much!!

**Comment by SaraAghajanzadeh** [comment]
Please consider releasing the training code 🙏

**Comment by markkua** [comment]
I'm working on it. coming soon

**Comment by markkua** [comment]
Training code has been released.
