### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by Keivin98** [prs-eth/Marigold#100]
I am getting the following error in the validation step: AssertionError: Wrong input shape torch.Size([3, 768, 1024]), expected [1, rgb, H, W]

In marigold_trainer.py function validate_single_dataset(), the input image is being squeezed to a 3 dimensional shape: `rgb_int = batch["rgb_int"].squeeze()  # [3, H, W]`, but in marigold_pipeline.py, it doesn't change the shape if the input is a tensor: 
```
elif isinstance(input_image, torch.Tensor):
            rgb = input_image
else:
            raise TypeError(f"Unknown input type: {type(input_image) = }")
input_size = rgb.shape
assert (
    4 == rgb.dim() and 3 == input_size[-3]
), f"Wrong input shape {input_size}, expected [1, rgb, H, W]"
```

**Comment by markkua** [comment]
Fixed.
