### ISSUE TITLE
NYUv2 Filled depth map

### ISSUE THREAD

**Issue by gaoxiangjun** [prs-eth/Marigold#114]
I downloaded NYUv2 from your link. However, I found that the filled depth map is the same as the raw depth map. Is there any problem?

I am new to this area, I wonder if people just calculate metrics using only raw depth maps or dense depth maps.
If raw nyuv2 depth map, everything is okay. If dense nyuv2 depth map, there might be a problem.

Looking forward to your reply. This problem confuses me a lot.

**Comment by markkua** [comment]
Hi, the NYUv2 dataset I uploaded only contains the raw depth predictions. The evaluation was conducted on these raw depth predictions only, since the dense version was obtained by naive bilateral interpolation.

**Comment by gaoxiangjun** [comment]
Hi bingxin, Thanks a lot!
