### ISSUE TITLE
Wandb logging is always interrupted unexpectedly

### ISSUE THREAD

**Issue by water221** [prs-eth/Marigold#115]
When I was training the model, I found that 'wandb' always interrupted abnormally, attached my log file below, can someone help me answer it  
The first figure is the visual display of 'wandb', the second figure is the running log of 'wandb', and the third figure is the training log of the project。
This training in the figure was abnormally interrupted at step 932, and the visualized loss was no longer updated.    
![image](https://github.com/user-attachments/assets/f5ce45a1-26aa-4815-97e0-5315d2e50aaa)
![image](https://github.com/user-attachments/assets/a200d04e-6e34-4705-8bdb-16c1018a71ab)
![image](https://github.com/user-attachments/assets/56021444-9b08-4e20-9ade-4fb32b871a88)

**Comment by markkua** [comment]
Hi, I haven't experienced this before. I would upgrade the packages and check the network. Otherwise, I suggest asking in wandb github.
