### ISSUE TITLE
conflict in .yaml file

### ISSUE THREAD

**Issue by Meghdad24** [prs-eth/Marigold#121]
when i want to create vir env from .yaml file by mamba command he told me that exist conflict between packages

I do this and be OK!

name: marigold
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - accelerate>=0.22.0
  - diffusers>=0.25.0
  - matplotlib>=3.8.2
  - scipy>=1.11.4
  - python=3.11 # It was changed
  - pytorch=2.0.1 # It was changed
  - pytorch-cuda=11.7
  - torchvision=0.15.2
  - pip:
    - transformers==4.32.1

**Comment by Meghdad24** [comment]
```
name: marigold
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - accelerate>=0.22.0
  - diffusers>=0.25.0
  - matplotlib>=3.8.2
  - scipy>=1.11.4
  - python=3.11
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - torchvision=0.15.2
  - pip:
    - transformers==4.32.1
```

**Comment by markkua** [comment]
resolved in https://github.com/prs-eth/Marigold/commit/62413d56099d36573b2de1eb8c429839734b7782
