### ISSUE TITLE
Can Marigold be trained from scratch?

### ISSUE THREAD

**Issue by resurgo97** [prs-eth/Marigold#126]
Is it really necessary to train Marigold in a fine-tuning manner?

Or have you reasoned about the possibility of training it from scratch?

Any insights, experiences, or opinions will be appreciated!

Thanks!

**Comment by markkua** [comment]
Hi, the main idea of this paper is to reuse the pretrained prior from SD. Training from scratch is not something we targeted for. I also tested it out though, in my training setting, it didn't converge to a reasonable result.
