### ISSUE TITLE
Inquiry About 3D Reconstruction Code Availability

### ISSUE THREAD

**Issue by CaiSir0075** [prs-eth/Marigold#128]
I hope this message finds you well. I am writing to inquire whether you would be willing to share the code used for the 3D reconstruction demonstrated in your recent work with Marigold-LCM. I am very interested in exploring the techniques and methodologies you employed, and having access to the code would greatly enhance my understanding and allow me to experiment further.

**Comment by markkua** [comment]
Hi. Our method is for depth estimation. To recover the 3D points, you need extra camera intrinsic, and the scale and shift of the depth. Please refer to this issue for details https://github.com/prs-eth/Marigold/issues/6
