### ISSUE TITLE
The training runs abnormally, and the memory is occupied at a certain step

### ISSUE THREAD

**Issue by zad37** [prs-eth/Marigold#129]
2024-10-18 21:38:14,708 - INFO -train.py - <module> >> device = cuda
 2024-10-18 21:38:14,712 - INFO -train.py - <module> >> Config saved to ./output/train_marigold/config.yaml

 The training process is always stuck in this section, I found that the storage disk memory is constantly occupied until the whole space is full, and when I try to terminate this command, I get the following associated error:

 ^Crsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at io.c(518) [generator=3.2.7]
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(713) [sender=3.2.7]
 2024-10-18 21:39:43,875 - INFO -train.py - <module> >> Code snapshot saved to: ./output/train_marigold/code_snapshot.tar
 2024-10-18 21:39:43,881 - INFO -train.py - <module> >> Effective batch size: 32, accumulation steps: 16
Traceback (most recent call last):
  File "/root/Marigold/train.py", line 266, in <module>
    assert len(cfg_data.train.prob_ls) == len(
AssertionError: Lengths don't match: `prob_ls` and `dataset_list`

Is this because the training code is causing a process to loop indefinitely, causing the corresponding memory to increase, or is it because I don't have enough disk memory, I've used an 800G of memory, and I still can't continue training. I would like to follow your advice and hope to get your help, thank you!

**Comment by zad37** [comment]
I solved this problem by making the following changes:

os.system(
    f"rsync --relative -arhvz --quiet --filter=':- .gitignore' --exclude '.git' --exclude 'code_snapshot.tar' . '{_temp_code_dir}'"
)

But then came a new mistake:

Traceback (most recent call last):
  File "/root/Marigold/train.py", line 266, in <module>
    assert len(cfg_data.train.prob_ls) == len(

I think these two problems are related, because I once caused this error due to insufficient memory caused by the first error, which made me very confused, I hope to get some help and advice, thank you.

**Comment by zad37** [comment]
The problem has been solved, thank you.

**Comment by kke19** [comment]
@zad37 Hi, Could you tell me how you solved this problem?

**Comment by zad37** [comment]
@kke19 This is actually a copy error, 'code_snapshot.tar' is constantly copying and enlarging itself, so you just need to not copy itself. I found this part of the code in train.py and made the following changes:

os.system(
f"rsync --relative -arhvz --quiet --filter=':- .gitignore' --exclude '.git' --exclude 'code_snapshot.tar' . '{_temp_code_dir}'"
)

This is essentially 'code_snapshot.tar' will copy all files in the output sibling list, as long as it excludes itself.

**Comment by markkua** [comment]
It might be that your output folder is not in `.gitignore`. You can consider adding `/output/` into `.gitignore`
