### ISSUE TITLE
License

### ISSUE THREAD

**Issue by emlcpfx** [prs-eth/Marigold#13]
Does the license mean that the software itself can’t be used for commercial purposes— as in, I can’t sell it or sell products using the repo— or does it mean the depth maps themselves can’t be used within a project— as in, the depth maps couldn’t be used to create an asset in VFX or gaming for commercial purposes?

**Comment by toshas** [comment]
We are working on this and will update you soon, stay tuned!

**Comment by Genlab-cg** [comment]
Yeah current lisence is not workable, it prevents us from adopting this great work to things like controlnet and sd extensions,  best option is MIT lisence. 
Most respect for the work you have done with Marigold.
We are exploring the option to use stable diffusion inpaint models to train depth and normal map as well , as the inpainting model supports concatenation method.
https://github.com/lorenzo-stacchio/Stable-Diffusion-Inpaint
Any feedback on that idea ?

**Comment by Denny-kef** [comment]
Would really be useful if this could be changed to an MIT license.  Such amazing work in monocular depth would be extremely useful in so many different applications!!

**Comment by markkua** [comment]
Hello,

We have updated the license to [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0). Commercial usage is now possible under the [LICENSE](https://github.com/prs-eth/Marigold/blob/main/README.md).

Best.

**Comment by emlcpfx** [comment]
Awesome, I’m excited to use this in production.
