### ISSUE TITLE
Other training metric are abnormal

### ISSUE THREAD

**Issue by zad37** [prs-eth/Marigold#130]
After the first training, I found that the experimental result only had the value of loss. Then I added "abs_rel", "rmse_log", "rmse_linear", "log10", "delta1_acc", "delta2_acc", "delta3_acc", "i_rmse", Indicators such as "silog_rmse" are trained again. I found that several metrics were abnormal, mainly including "abs_rel", "rmse_log", "log10", "silog_rmse". abs_rel" indicator showed a large number of strange negative values, which is theoretically impossible; The "rmse_log", "log10", and "silog_rmse" indicators all contain nan. This makes me very confused. My data set uses a small part of hypersim, and the related functions use metirc. I would like to know what causes this, and hope to get some suggestions from you.

**Comment by markkua** [comment]
Hi. Sorry, I don't get your question. The evaluation metrics are only used in validation and should not affect training.

**Comment by zad37** [comment]
Sorry, thanks for your help, I am a beginner, I seem to have made a low-level mistake, that is, trying to put the evaluation indicators into the training process, and observing the changes of these evaluation indicators on wanb, which made some of the results strange. Thanks again for your help!
