### ISSUE TITLE
Depth Map Prior

### ISSUE THREAD

**Issue by sam-thomas-dd** [prs-eth/Marigold#137]
Thanks for the great work!

Is it possible to use an existing depth map as a prior to refine / infill?

**Comment by Haozong-Zeng** [comment]
I am also curious on that, e.g. there are always some invalid pixels on the depth map from depth camera.

**Comment by nandometzger** [comment]
Please have a look at our most recent preprint, that might solve your problem: https://github.com/prs-eth/Marigold-DC

**Comment by sam-thomas-dd** [comment]
I just came back here to add this, found it last night. Looks perfect!
