### ISSUE TITLE
Acknowledgment and Concerns :Training code and License Ambiguities

### ISSUE THREAD

**Issue by mr-lab** [prs-eth/Marigold#16]
First and foremost, I'd like to express my sincere appreciation for the remarkable work you've done with [Marigold](https://github.com/prs-eth/Marigold). I view this project as a significant breakthrough in the field of computer graphics.

This endeavor has the potential to extend beyond its current capabilities with depth generation, opening doors for diverse applications given the right dataset. However, there is a critical need for training code to adapt this model for tasks such as generating normal, displacement, metallic maps, and more.

Regrettably, the project's license is presently unclear, posing a hindrance to its utilization in our projects. The ambiguity surrounding whether the generated depth maps can be employed commercially, coupled with the restriction on the commercial use of the code, renders the project impractical for our needs.

**Comment by markkua** [comment]
Hello,

We have updated the license to [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0). Commercial usage is now possible under the [LICENSE](https://github.com/prs-eth/Marigold/blob/main/README.md).

Best.

**Comment by mr-lab** [comment]
<3 <3 <3 will start working with it now !! thank you 
list of things would test is : 
integrate it with our tile system 
test   hires fix logic on it 
integrate it with PatchFusion
and i know Training code  is too much to ask for but if you ever push that , i would be super busy !! 
because this extends above depth map training or normal maps or any other maps 
this could be gold imagine this you have img one of a tree  then go decorate that tree and retake the same photo only difference is  the decoration , train on a data set of natural trees and decorated trees , and you have a decoration model 
i know the example is silly , but it can be implemented to cover wide range of application , from art to 3d to medical and  industrial applications 
the main concept is you have x that you want it to be y without changing anything about x structure .... xray simulations 
infrared camera simulations ...house renovation simulations  endless possibilities , if only i have the training code i would be sure if all of those possibilities  are possible 
again thanks and  my deepest gratitude and appreciation to the team , cheers
