### ISSUE TITLE
Video depth map deflickering

### ISSUE THREAD

**Issue by Fannovel16** [prs-eth/Marigold#17]
Depth maps generated from video frames by Marigold is obiviously flickering. While this can be partially fixed by setting high n_repeat and fixed seed, such method is inefficent imo. Is there any way to use previous video frame/depth map to condition the diffusion process?

**Comment by darkzbaron** [comment]
+1

**Comment by leavittx** [comment]
+1

**Comment by pablodawson** [comment]
https://github.com/pablodawson/Marigold-Video May help, it is very rough atm

**Comment by markkua** [comment]
Please check out our tutorial on Diffusers](https://huggingface.co/docs/diffusers/using-diffusers/marigold_usage#frame-by-frame-video-processing-with-temporal-consistency) for details.
![video_obama](https://huggingface.co/datasets/huggingface/documentation-images/resolve/25024b5443a6c1357492751fd09355bd3f967845/marigold/marigold_obama.gif)
)
![depth_obama](https://huggingface.co/datasets/huggingface/documentation-images/resolve/25024b5443a6c1357492751fd09355bd3f967845/marigold/marigold_obama_depth_independent.gif)

**Comment by markkua** [comment]
There is a trick to improve temporal consistency. 

Please check out our [tutorial on Diffusers](https://huggingface.co/docs/diffusers/using-diffusers/marigold_usage#frame-by-frame-video-processing-with-temporal-consistency) for details.

![](https://huggingface.co/datasets/huggingface/documentation-images/resolve/25024b5443a6c1357492751fd09355bd3f967845/marigold/marigold_obama.gif)

![](https://huggingface.co/datasets/huggingface/documentation-images/resolve/25024b5443a6c1357492751fd09355bd3f967845/marigold/marigold_obama_depth_consistent.gif)
