### ISSUE TITLE
Any plan to train specialized ControlNet/ControlLora?

### ISSUE THREAD

**Issue by Fannovel16** [prs-eth/Marigold#18]
Thanks for the work you've done on Marigold. This is a revolutionary depth map estimator with extreme details compared to previous methods. Imo, one noticable application of it is [ControlNet](https://arxiv.org/pdf/2302.05543.pdf) preprocessor. The problem tho is that current [depth map ControlNet](https://github.com/lllyasviel/ControlNet-v1-1-nightly?tab=readme-ov-file#controlnet-11-depth) was only trained on less detailed dataset so it can't get all details from depth map generated by Marigold.

**Comment by toshas** [comment]
Please check out the recipe here: https://huggingface.co/docs/diffusers/using-diffusers/marigold_usage#marigold-for-controlnet
