### ISSUE TITLE
Colab NameError: name 'pipe' is not defined

### ISSUE THREAD

**Issue by krigeta** [prs-eth/Marigold#19]
this is the error I am getting while using the Google colab notebook, Please help

```
---> 29         pipeline_output = pipe(
     30             input_image,
     31             denoising_steps=10,     # optional

NameError: name 'pipe' is not defined
```

**Comment by markkua** [comment]
Hello, 
Thanks for running our Colab demo.

Please run all the preparation cells above before running the inference cell. The variable `pipe` is defined in the cell [🏇 2.1 Initialize pipeline](https://colab.research.google.com/drive/12G8reD13DdpMie5ZQlaFNo2WCGeNUH-u#scrollTo=1BYxXKkkrHpW&line=1&uniqifier=1).

(unrelated to this issue: I just made an update to fix another small bug with sample images. It's recommended to use the updated notebook)

Best.
