### ISSUE TITLE
About training on real images 

### ISSUE THREAD

**Issue by Coco32123** [prs-eth/Marigold#2]
Thanks for sharing your code and model. The depth visualization is really awesome, especially sharp edges.

I noticed that both training datasets(Hypersim and Virtual KITTI) were synthetic datasets. Have you ever tried to train on real dataset?

**Comment by toshas** [comment]
Training with synthetic data is an integral part of Marigold. For more insights, please see the "Training on synthetic data" paragraph of Sec. 3.3 of our paper: https://arxiv.org/pdf/2312.02145.pdf
