### ISSUE TITLE
How to write depthmap in pfm

### ISSUE THREAD

**Issue by rupher3222** [prs-eth/Marigold#24]
Thank for your amazing contributions.
By the way, since my code which can generate 3d point clouds using depthmap needs pfm format of depthmap, so I want to write depth_pred in pfm. How can I do this?

**Comment by markkua** [comment]
We have provided the predicted depth map as numpy array `depth_pred` in the script. You can try to save it as whatever format you prefer. For pfm, you could try with [imageio](https://imageio.readthedocs.io/en/v2.33.1/formats/formats_by_plugin.html#formats-by-plugin).

**Comment by rupher3222** [comment]
> We have provided the predicted depth map as numpy array `depth_pred` in the script. You can try to save it as whatever format you prefer. For pfm, you could try with [imageio](https://imageio.readthedocs.io/en/v2.33.1/formats/formats_by_plugin.html#formats-by-plugin).

I deeply appreciate your thoughtful and detailed response to my inquiry. Your assistance has been immensely helpful. Thank you very much.
