### ISSUE TITLE
Can this algorithm be used to obtain real-world distance to an object?

### ISSUE THREAD

**Issue by jackhawa** [prs-eth/Marigold#25]

**Comment by toshas** [comment]
Stay tuned ;)

**Comment by tcourat** [comment]
Google just released a paper very similar to this one (diffusion models for depth prediction). They claim being able to predict **metric depth** if you know camera FOV : https://diffusion-vision.github.io/dmd/

**Comment by booker-max** [comment]
> Google just released a paper very similar to this one (diffusion models for depth prediction). They claim being able to predict **metric depth** if you know camera FOV : https://diffusion-vision.github.io/dmd/

很可惜，没有开源代码
