### ISSUE TITLE
Question on the output

### ISSUE THREAD

**Issue by bhowiebkr** [prs-eth/Marigold#27]
Is the npy file a numpy array? If so what are the values in? If the model is trained off synthetic data and if the npy is what I think it is, does that mean it'll be in real world or some other linear dimensional scaled value? BTW it works great! takes a long time though.

Here's me face
![Bryan_1k_pred](https://github.com/prs-eth/Marigold/assets/904170/731c352c-4243-4156-8a1a-2bb7a1d35d60)

Pretty amazing it's able to figure out all the hair. Still trying to fully understand from the paper how it works.

**Comment by Fannovel16** [comment]
@bhowiebkr 
> Is the npy file a numpy array? If so what are the values in?

Range [0, 1]. You can inverse the values to get similar results to MiDaS or LeRes

**Comment by bhowiebkr** [comment]
Thanks, I'll try these settings. With the defaults this 1k image must of took 20-30min on a 4090.

**Comment by ShnitzelKiller** [comment]
Is there some kind of shift to the values? My results with this seem to have depth values way too close to the camera. For example, with this:
![image](https://github.com/prs-eth/Marigold/assets/6132502/55ae31cc-eb58-4367-a27e-5d36e0c06b48)

If I project the depth values from the .npy file into a point cloud using a linear camera transform, I get this warped result where points have near 0 depth, and are basically touching the camera point:
![image](https://github.com/prs-eth/Marigold/assets/6132502/00fa0c83-8c0f-4d38-9650-7a7e47b2c0b4)

**Comment by markkua** [comment]
Hello @ShnitzelKiller, Marigold predicts affine-invariant depth, which is up to unknown scale and shift factors. This means, in practice, you might have to pick the best scale and shift factors yourself. Please refer to [this issue](https://github.com/prs-eth/Marigold/issues/6#issuecomment-1850568874) for more details.
