### ISSUE TITLE
Try to convert depth maps to normal maps

### ISSUE THREAD

**Issue by snowflakewang** [prs-eth/Marigold#29]
Hello, thank you for your brilliant work!
I am a student from USTC, who is a novice in 3D Vision. I run your code on my DIY cases and it works well. Upon your impressive results, I want to make some exploration related to normal maps. In your paper, I notice that you mentioned _colored as normals_ in Figure 5. I wonder whether those are authentic surface normals that we usually use?
If yes, how can I get those normals based on your code?
Thanks a lot!!! :)
![as](https://github.com/prs-eth/Marigold/assets/83908155/edc6b18c-d769-477a-a2d1-f3ba20df7432)

**Comment by markkua** [comment]
Hello, please refer to [this issue](https://github.com/prs-eth/Marigold/issues/6#issuecomment-1850568874) about converting depth maps to point clouds, from which you can calculate the normals :D.
