### ISSUE TITLE
Why, when estimation a sequence, the depth between the frames is always different?

### ISSUE THREAD

**Issue by ATERUBER** [prs-eth/Marigold#3]
Why, when estimation a sequence, the depth between the frames is always different. Is it possible to averaged the value of the depth, like a implemented in Zoedepth?

**Comment by toshas** [comment]
Because estimation happens independently for each frame by design. There could be extensions of our method to aid this issue. 

Please upvote this post so that we can estimate the importance of working on this issue

**Comment by emlcpfx** [comment]
Temporally consistent video estimation would be HUGE. I have a set of VFX shots that need this right now.
