### ISSUE TITLE
why the paper was named Marigold?

### ISSUE THREAD

**Issue by ywcmaike** [prs-eth/Marigold#31]
As the title said, why the paper was named Marigold? I'm curious about this.

**Comment by ShengyuH** [comment]
Great question! You can find the answer if you dig into the last sample shown in page 14 of our paper.

**Comment by nandometzger** [comment]
Moreover, there are some other easter eggs related to the Marigold name hidden in the paper. I will no spoil all the fun for you, but there are two on the title page :)

**Comment by markkua** [comment]
In some interpretations of the Greek mythology, King Midas, has a daughter named Marigold.
In this easter-egg painting we put in the paper, Marigold is looking up to Midas (referring to the method [MiDaS](https://github.com/isl-org/MiDaS)).

<img width="1038" alt="image" src="https://github.com/prs-eth/Marigold/assets/45253439/7aec9651-a477-4424-8241-847ebc0a196c">
