### ISSUE TITLE
The main difference between this paper and other density visual prediction methods utilizing the diffusion model

### ISSUE THREAD

**Issue by hero-y** [prs-eth/Marigold#36]
Hello, thank you for your excellent work. I've noticed several papers on density visual prediction utilizing the diffusion model, and I'm interested in understanding how your paper differs from them. Is the main distinction that other papers do not utilize the pretrained SD? The discussion in your paper seems a bit brief. If you could provide further clarification, it would be greatly appreciated. Thank you!

**Comment by ShengyuH** [comment]
Can you add a reference to "several papers on density visual prediction utilizing the diffusion mode" before we even start this discussion?
