### ISSUE TITLE
Request: Make model available in Onnx and .pt format.

### ISSUE THREAD

**Issue by brentjohnston** [prs-eth/Marigold#37]
I am working with a custom version of a program called depthviewer and am currently trying to help the dev integrate the onnx version of depth-anything (tiktok model that kust released) he now has marigold working but it works outside of Unity.

I have found marigold results to be much superior for single images when converting to 3d than depth-anything, the issue is I have tried python conversion scripts to convert to a .pt and they do not work due to missing config.

Is there any way you guys can release the model in onmx format and also pt format?

**Comment by markkua** [comment]
You can find the pytorch model file (.bin) here: https://huggingface.co/Bingxin/Marigold/tree/main

**Comment by brentjohnston** [comment]
Yes I know this, the point was I needed it in onnx and .pt format for the depthviewer application.
