### ISSUE TITLE
About evaluation protocol

### ISSUE THREAD

**Issue by jhq1234** [prs-eth/Marigold#40]
Hi, I'm new to this field, and I am impressed by your outstanding work. Thank you for sharing your code! I have a question regarding the evaluation protocol details.

From the paper in the evaluation protocol section, the evaluation method of Marigold is described as follows.
"When we first align the estimated merged prediction m to the ground truth d with the least squares fitting, this step gives us the absolute aligned depth map a = m × s + t, in the same units as the ground truth."

Does this mean that the process described above proceeds in the following sequence?

(1) Obtain the depth map 'm' from the Diffusion model.
(2) Refine 'm' through least squares fitting with the ground truth.
(3) Estimate s and t to obtain the aligned depth map, a = m × s + t.

Thank you for reading my question. I am confused about whether the equation a = m × s + t is directly derived through least squares fitting, or if it requires separate calculation. If it's not too much trouble, could you please share the code for the evaluation protocol? Thank you!

**Comment by markkua** [comment]
Hello,

There is no "refinement" process. Least squares fitting is only used for estimating the scale `s` and shift `t` factors, to bring affine-invariant depth prediction to metric space, only for evaluation.

The evaluation code is comming soon. Stay tune.

Best.
