### ISSUE TITLE
Stable Diffusion fine-tuning problem

### ISSUE THREAD

**Issue by 838959823** [prs-eth/Marigold#42]
During fine-tuning for depth estimateaion conditioned on input image, how to deal with the text prompt required in the original pre_trained text-to-image Stable Diffusion model?

**Comment by saqib736** [comment]
As far as i understand, you can just pass the empty prompts.

**Comment by billie2jean** [comment]
I cannot understand the fine-tuning, i think it is a process of pre-training for getting the CKPT, and also not find the part corresponding to fine-tuning in the code. I wanna ask for your help, pls.

**Comment by saqib736** [comment]
> I cannot understand the fine-tuning, i think it is a process of pre-training for getting the CKPT, and also not find the part corresponding to fine-tuning in the code. I wanna ask for your help, pls.

Fine-tuning means training the pre-trained stable diffusion model on your specific dataset. This repository doesn't contain the training code yet; only the testing/inference code is available.

If you want to train or fine-tune the model on your dataset or any other dataset, I have written the training code for Marigold. You can find it on my GitHub here: [training code for Marigold](https://github.com/saqib736/Depth_Estimation/blob/958248bd3125200bef1150f0aa2d330966fa7564/stable_difusion/train_sd.py).

**Comment by billie2jean** [comment]
Thx😊, :)

**Comment by billie2jean** [comment]
Thx, :)

**Comment by markkua** [comment]
Training code has been released.
