### ISSUE TITLE
Different results from huggingface demo and github repo

### ISSUE THREAD

**Issue by ActonLee** [prs-eth/Marigold#43]
Hi, I am trying to produce a depth map from a single image using Marigold. I have tried the huggingface demo and also used github repo to run the model locally with the save single photo. But I got different results:
![114_depth_colored](https://github.com/prs-eth/Marigold/assets/88582462/e6823f98-b4a9-4294-9312-2e4ed5bf96a4)
![114_pred_colored](https://github.com/prs-eth/Marigold/assets/88582462/a1859667-70c5-4b33-8a68-03bf3e7a27dc)
the former one's from higgingface demo, while the latter one's from github repo running locally. I wanna know if there's any difference like config between them?

**Comment by markkua** [comment]
Could you provide the input image and the settings (denoising steps, ensemble size) of both results? We will look into it afterwards.

**Comment by ActonLee** [comment]
Hi, all the settings are as default (ensemble size 10, denoising steps 10). I think it's the different versions of your code that resulted in the different results. Specifically, on huggingface, the SHA is 02cdfa5280d50afad976fdb6512de02011042c1c, which is not the newest version of your code.

**Comment by ActonLee** [comment]
@markkua Aside from that, could I know why you modify the RGB normalization at the version 9ed49d70e46eb78b29460797015a156165116bfa? I think that's where the problem lies.

**Comment by ActonLee** [comment]
Thanks and glad to see that.
