### ISSUE TITLE
Vector displacement? [feature request]

### ISSUE THREAD

**Issue by al3dv2** [prs-eth/Marigold#48]
Hi I want to know if it's possible to add vector displacement ? it's allow to get better result than depth map on 3d objects 
depth vs vector : 
![VectorDisp02](https://github.com/prs-eth/Marigold/assets/157552424/e26820cf-4afc-455c-8ba2-c72e0855a727)

**Comment by toshas** [comment]
Thanks for your interest, @al3dv2! Could you please elaborate on how you would tackle converting Hypersim pre-rendered depth maps into this format? Alternatively, if you know another dataset in this format, I would be curious to learn.
