### ISSUE TITLE
How to generate the Point Clouds shown in the paper ?

### ISSUE THREAD

**Issue by PHOENIXFURY007** [prs-eth/Marigold#49]
Can you share how the depth maps were used to generate the point clouds?
I checked this issue ( https://github.com/prs-eth/Marigold/issues/6 ), but it doesn't specify any method on how to generate the points clouds and visualize them

Also, is it possible to use multiple images showing different individual parts of a scene, and generate depth maps from them?  And then use those multiple-depth maps to connect the different point clouds to form the whole scene together without using stitching ?

**Comment by nandometzger** [comment]
Thank you for your question.

We used a standard pinhole camera model to unproject the 2.5D depths into 3D space. Note that we used the camera parameters of the corresponding dataset for this. For in-the-wild samples, we set to principle point to half of the image dimensions, and guessed the shift and focal length. Note that the unknown focal-length aborbs the unknown scale.
We used matplotlib to render the dataset samples from consistent angles and zoom-levels. For the in-the-wild samples (on the title-page), we used the meshlab.

Hope that helps :)
