### ISSUE TITLE
Try to use it in a real-world scenario

### ISSUE THREAD

**Issue by FatJiaFei** [prs-eth/Marigold#5]
Thank you for sharing, I tried to use it in the real scene, but the depth map I got is very strange after converting it into a point cloud, I would like to ask how you converted the depth map into a point cloud file.

**Comment by JUGGHM** [comment]
> Thank you for sharing, I tried to use it in the real scene, but the depth map I got is very strange after converting it into a point cloud, I would like to ask how you converted the depth map into a point cloud file.

Personally I think proper intrinsics should be chosen.

**Comment by markkua** [comment]
Thanks for your interest in our work.
Please refer to the answers at https://github.com/prs-eth/Marigold/issues/6#issuecomment-1850568874 and https://github.com/prs-eth/Marigold/issues/6#issuecomment-1850903378.
