### ISSUE TITLE
How should I set up the dataset

### ISSUE THREAD

**Issue by billie2jean** [prs-eth/Marigold#60]
I set up a new folder in the root , named kitti_data, and placed the KITTI dataset in it
BUT when I run the code:
 `bash script/eval/21_infer_kitti.sh`   
and there is a KeyError: "filename './2011_09_26/2011_09_26_drive_0002_sync/image_02/data/0000000069.png' not found".

I'm a rookie, u know, and I can't figure this out.

**Comment by markkua** [comment]
As described in this section: https://github.com/prs-eth/Marigold?tab=readme-ov-file#-evaluation-on-test-datasets,
you are supposed to create a folder wherever you like, e.g. `/data`, and create a subfolder in it called `/data/kitti` and put kitti data in it, tar it without compression as `kitti_eigen_split_test.tar`.

Then `export BASE_DATA_DIR=/data`. The scripts will look for `${BASE_DATA_DIR}/kitti/kitti_eigen_split_test.tar` as input data.

Alternatively, you can also edit the corresponding paths [in the script](https://github.com/prs-eth/Marigold/blob/be3065260f19b02a807c93b572a6d10ab396bd57/script/eval/21_infer_kitti.sh#L8) and [in the config](https://github.com/prs-eth/Marigold/blob/be3065260f19b02a807c93b572a6d10ab396bd57/config/dataset/data_kitti_eigen_test.yaml#L3)
