### ISSUE TITLE
Inconsistent results in Table 1 and ablation study.

### ISSUE THREAD

**Issue by indu1ge** [prs-eth/Marigold#66]
Hi, I notice that the results reported in Table 1 and those reported in ablation studies are inconsistent.
![image](https://github.com/prs-eth/Marigold/assets/79347888/461b1d61-c258-4bbf-aa74-d2fc8b2c971b)
![image](https://github.com/prs-eth/Marigold/assets/79347888/28b0aba7-93d7-4dd6-9f91-969ffc7eb039)
Could you please tell the difference between the two models?

**Comment by markkua** [comment]
They are evaluated on different subsets.

For Table 1, please refer to "4.2/Evaluation datasets".

For Table 2, please refer to  Section 4.3:
> Two zero-shot validation sets are selected for the ablation studies – the official training split of NYUv2 [31], consist- ing of 785 samples, and a randomly selected subset of 800 images from the KITTI Eigen [14] training split. Refer to supplementary sections for extra ablations and discussion.
