### ISSUE TITLE
problems about training dataset

### ISSUE THREAD

**Issue by luochunfen** [prs-eth/Marigold#67]
Hi authors! I find that you probabilistically choose the KITTI or Hypersim dataset and draw the mini batch from it when you are training. Could you explain the reason for that? Why don't you resize or crop the training dataset to the same size and mix the two datasets to draw the mini batch?

**Comment by markkua** [comment]
It's a design choice. Reasons:
- Resizing to the same shape would change the aspect ration. 
- Cropping would lose content affect the projective geometry. And the short edge of KITTI is too small.
- The size of mini batch is only 2.
