### ISSUE TITLE
how to inference one image on multi-gpu for faster processing?

### ISSUE THREAD

**Issue by mikebilly** [prs-eth/Marigold#68]

**Comment by markkua** [comment]
Multi-GPU inference is not supported yet in this code. For faster processing, you can try our LCM model.

**Comment by markkua** [comment]
That's currently beyond our plan. You can implement by running [this function](https://github.com/prs-eth/Marigold/blob/0e4525c34b465f6b6b9cc8006260075b574947e8/marigold/marigold_pipeline.py#L370) in parallel.

**Comment by markkua** [comment]
One simple solution is to run each ensemble member in parallel, then gather them to do ensemble.
