### ISSUE TITLE
About the predictions of reproduced model

### ISSUE THREAD

**Issue by indu1ge** [prs-eth/Marigold#69]
Hi, we reproduced Marigold according to the paper. The first figure is the depth predicted by the model we reproduced. The second figure is the prediction of Marigold's official weight. Compared with Marigold's prediction, our prediction is not smooth. Actually, there is a lot of noise Besides, the model seems to only focus on the foreground, and the depth prediction range is small. Do you have any suggestions on this?
![ec90ff252012665d3f7d0df48cfd5785](https://github.com/prs-eth/Marigold/assets/79347888/e61990c0-fe39-494a-b244-b4e11017eace)
![7d6cae4ec70b3bb90c42c001029e1e2d](https://github.com/prs-eth/Marigold/assets/79347888/a819620c-8ffb-43fa-a46b-41bc16e882df)

**Comment by markkua** [comment]
Training code has been released. You can check it out.

**Comment by myc634** [comment]
Hi, could you please tell me where is the bug? I try to tune the training code and meet the same issue

**Comment by indu1ge** [comment]
You can try the 20k iter checkpoint.

**Comment by myc634** [comment]
I tried 20k iter, and both of them seem noisy. I try to modify the code with `accelerator`, but all of the results seems noisy
