### ISSUE TITLE
how to convert a HF Diffusers saved pipeline to a Stable Diffusion checkpoint?

### ISSUE THREAD

**Issue by frankchieng** [prs-eth/Marigold#72]
I wanna to convert the current UNet, VAE, scheduler, tokenizer and Text Encoder diffusers model structure to a single safetensors checkpoint file then i can load in comfyUI,any advice or solution?

**Comment by LastTargaryen** [comment]
Is this a joke...? Uhm YES there is a comfyui solution, LOL

https://github.com/kijai/ComfyUI-Marigold
