### ISSUE TITLE
the test results seem have much noise

### ISSUE THREAD

**Issue by visonpon** [prs-eth/Marigold#73]
Hi, thanks for sharing this wonderful work, I tried to test  but the depth map seems have much noise.
![1221503220](https://github.com/prs-eth/Marigold/assets/11517731/76de7826-5c7f-4e51-b8a4-47d78ec2aa71)

**Comment by markkua** [comment]
Can you share the input image and inference setting?

**Comment by visonpon** [comment]
my setting just follow yours in `Run inference with DDIM (paper setting)`, and the input images are from the moive - 周处除三害(The Pig, The Snake and The Pigeon)

**Comment by markkua** [comment]
Without seeing the actual input image, it's hard for me to analyze. 
I recommend trying without ensembling (ensemble size = 1). For challenging areas, it's possible that the model is uncertain and the ensemble members are too different.

**Comment by visonpon** [comment]
@markkua my test image likes bellow:
![2088620377](https://github.com/prs-eth/Marigold/assets/11517731/1bfc801a-8e51-4f82-a103-b88c9898473b)
it's weird testing on huggingface is normal but unnormal in local .

**Comment by YacineDeghaies** [comment]
@visonpon did you solve this ? if yes, how ?
