### ISSUE TITLE
Regarding the training convergence

### ISSUE THREAD

**Issue by Yifehuang97** [prs-eth/Marigold#74]
Hi,

Thanks for your great work! 
I just curious about how many training steps it take to show a reasoning denoising result.

Thanks for your help!

**Comment by markkua** [comment]
Hi it took me around 20K iteration to converge.

**Comment by Yifehuang97** [comment]
Thank you for your reply!

I have a question regarding your previous unsuccessful experiment. Typically, how many iterations do you run before determining that an experiment has failed? Do you wait until the experiment completes, or do you stop early if it appears unsuccessful?

I ask because I am currently fine-tuning SD on a different image-related domain (albedo, rather than depth as in your task). Understanding your past experiment experiences would be very helpful for my work.

Thank you so much for your assistance!

**Comment by Yifehuang97** [comment]
I have another question regarding the choice of image conditioning methods. Have you conducted experiments on fine-tuning the image-variation SD base model or by adding an IP-Adapter to inject the image?
Thank you!

**Comment by markkua** [comment]
> how many iterations do you run before determining that an experiment has failed

This depends on the experiment setting. There is no universal rule for it.

> Have you conducted experiments on fine-tuning the image-variation SD base model or by adding an IP-Adapter to inject the image?

In our paper, we only use the most straightforward direct fine-tuning.
