### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by saqib736** [prs-eth/Marigold#75]
Hi, Thank you guys for your amazing work. 

I would like to use the training process on my custom dataset in which i have RGB images with corresponding depth map.

Can you guys guide me a bit how can I process my dataset to use with the provided training script.

Regards,

**Comment by markkua** [comment]
Please refer to the [dataset class](https://github.com/prs-eth/Marigold/blob/main/src/dataset/base_depth_dataset.py) and [Hypersim preprocessing script](https://github.com/prs-eth/Marigold/blob/main/script/dataset_preprocess/hypersim/README.md) for details.
