### ISSUE TITLE
the prediction on in-the-wild example is noisy

### ISSUE THREAD

**Issue by indu1ge** [prs-eth/Marigold#76]
Hi, I trained the model with your official training code. The quantitive results are consistent with the paper. But the qualitive result is relatively poor with much noise. Could you provide some suggestions on that?
![Screenshot_2024_0603_160949](https://github.com/prs-eth/Marigold/assets/79347888/f2f4bd9b-a554-4d8f-88a2-d672834c241c)

**Comment by markkua** [comment]
How many iterations have you trained? I would recommend training further, as qualitative results might still be improved although one might not observe in the quantitative results.
