### ISSUE TITLE
Why set NaN depth values to zero on preprocessing?

### ISSUE THREAD

**Issue by gkmocastro** [prs-eth/Marigold#78]
Greetings. Thank you for your amazing work. I would like to ask why do you guys choose to set the NaN Pixels on the depth image (or invalid geometry pixels, as said by owners of Hypersim) to zero on the preprocessing script? 

`plane_depth[~valid_mask] = 0`

Im doing the same kind of preprocess on my research and just wanted to know if isn't better set it to 255, since those images usually has windows and other kinds of far objects that doesnt belong to the structure itself (example below)

![output](https://github.com/prs-eth/Marigold/assets/110259878/f3a5983f-6287-4f6a-a946-290665eba694)

**Comment by markkua** [comment]
In the processed depth maps, 0 represents “invalid” (following the convention of NYUv2). In this way we don’t have to store a separate validity mask. 

You are right that most of these pixels should be assigned a large depth value. This is done in the [data loading](https://github.com/prs-eth/Marigold/blob/10e775f9359a0d07cb4e56009c91b53fa45f44f2/src/dataset/base_depth_dataset.py#L237).
