### ISSUE TITLE
Broken Arguments

### ISSUE THREAD

**Issue by Bolt-Scripts** [prs-eth/Marigold#8]
https://github.com/prs-eth/Marigold/blob/cc78ff3033f5804cadf8523ed11b6bbf0d025077/run.py#L64C16-L64C16
The bitwise NOT operator ~ should not be used with boolean values the same way ! is used in other languages.
It turns it into a number and doesn't work right when checked later.

Worse than that and how I know nobody bothered to test this:
When you fix the above issue and it actually returns false when checking resize_input, "image" never actually gets assigned and will throw an error.

I'm too lazy to make a pull request though.

**Comment by markkua** [comment]
Thanks for catching the issue. I fixed it and will close this issue.
