### ISSUE TITLE
How to Manage the Large Hypersim Dataset for Reproduction?

### ISSUE THREAD

**Issue by haopengmai** [prs-eth/Marigold#80]
Thank you for your outstanding contribution to the community!

I am trying to reproduce this work, but the Hypersim Dataset(~1.9TB) exceeds my local and cloud storage capabilities. What strategies or tools do you recommend for handling such a large dataset, especially for efficient access and training?

**Comment by haopengmai** [comment]
<img width="592" alt="image" src="https://github.com/prs-eth/Marigold/assets/127769758/d4bb07b9-9a2d-4aa7-81e6-ee90d7437308">

I noticed that you mentioned using 54K samples for training. To better understand and reference your experimental setup, could you kindly provide some information on the approximate memory usage of this dataset during training?

Your insights would be greatly helpful for my research.I sincerely appreciate it.(感谢大佬！)

**Comment by water221** [comment]
> The processed Hypersim dataset is much smaller. You can download and process it part-by-part (need some modifications to the preprocessing script though).

Can you tell me how many Gs there are in the processed Hypersim dataset, and can you provide a modified preprocessing script? I am a beginner in this area and I would appreciate it if you could provide it

**Comment by markkua** [comment]
The processed training set would be around 95GB.
