### ISSUE TITLE
Multi-GPU Training

### ISSUE THREAD

**Issue by xyclone10** [prs-eth/Marigold#84]
Hello! thank you for your amazing work! Is the training code already supported for multi-GPU training or still not yet supported?

And I want to correct something from the training instruction:
`python train.py --resume_from output/marigold_base/checkpoint/latest`

I think the correct one is:
`python train.py --resume_run output/marigold_base/checkpoint/latest`

Thank you!

**Comment by cr333** [comment]
Fix in #93.
