### ISSUE TITLE
Any reason for not using vae.std to generate RGB latent?

### ISSUE THREAD

**Issue by Jerrypiglet** [prs-eth/Marigold#86]
Hi there, I notice the pipeline of Marigold is different from the original SD pipeline in that, when encoding RGB/depth into latents, instead of doing something like `vae.encode(pixel_values).latent_dist.sample()`, the implementation uses function `def encode_rgb` where only the mean of the vae distribution is used as latent (see [here](https://github.com/prs-eth/Marigold/blob/main/marigold/marigold_pipeline.py#L468)), without adding `std * sample` as in [here](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/autoencoders/vae.py#L788). Is there a reason for this, to remove the randomness of the vae encoding?

**Comment by markkua** [comment]
Hi, as we are trying to do depth estimation, which is supposed to be deterministic unlike generation tasks. We intentionally did this to remove undesired randomness.
