### ISSUE TITLE
The purpose of using v_prediction as the target?

### ISSUE THREAD

**Issue by yongmayer** [prs-eth/Marigold#88]
Thank you so much for sharing this amazing work!
Could you shade some light on why v_prediction is chosen as the prediction type and "get_velocity" as the target? What are the benefits of doing so over other options, say using noise as the target?
Looking forward to your comments.

**Comment by markkua** [comment]
Hi, we simply follow the pretrained model we used (SD-v2), which was fine-tuned from SD-v2-base using v_prediction.
