### ISSUE TITLE
The demo 3D looks ok but not match with the predicted depth image

### ISSUE THREAD

**Issue by N-NEJATISHAHIDIN** [prs-eth/Marigold#90]
Hi,

I am trying to use the predicted depth image to generate the 3D point cloud of an indoor scene.
![000110000010101](https://github.com/prs-eth/Marigold/assets/60449580/895bf763-db44-4236-b7fe-cc3a3369c45e)

When I generate the depth image based on what you have in the demo or Colab and compute the 3D, this is what I get:
![Screenshot from 2024-06-24 19-52-51](https://github.com/prs-eth/Marigold/assets/60449580/ae364165-d4a9-43d4-9255-665d832e8709)

But when I use the demo to get the 3D, I get the following point cloud:
![Screenshot from 2024-06-24 19-55-03](https://github.com/prs-eth/Marigold/assets/60449580/512c0121-efdf-4d93-9e00-e3a6b07b899b)

I was wondering what could be the possible reason for this weird result, or could you provide the code that generates the 3D from the estimated depth (based on demo)?

**Comment by markkua** [comment]
Hi, the predicted depth is up to unknown scale and shift. To get the desired 3D point cloud, you might need to use other methods to estimate these two factors, e.g. aligning to some in-distribution metric depth methods, or eyeballing.
