### ISSUE TITLE
How to organize the vkitti data

### ISSUE THREAD

**Issue by Larissa0829** [prs-eth/Marigold#91]
Hello, I want to know how to organize the vkitti data?

I want to try training effects in two scenarios first, one for train and the other for val. The data organization is shown in the figure below:
![image](https://github.com/prs-eth/Marigold/assets/142070036/68514cb2-ddc7-41fd-8bda-fbde10b389e8)
But during the training, the error was reported:
`KeyError: "filename './rgb/Scene02/clone/frames/rgb/Camera_0/rgb_00008.jpg' not found"`
But I checked the folder and it was there.

How can I fix it? thank you！

**Comment by water221** [comment]
Hello, I am a beginner in this area. Recently, I have been reproducing this article and encountered the same problem. Have you solved this problem? If you know how to set up a vkitti dataset, would it be convenient to let me know? Thank you very much
