### ISSUE TITLE
issue with reproducing results in the paper

### ISSUE THREAD

**Issue by yongmayer** [prs-eth/Marigold#96]
Hi,

I try to reproduce the results in the paper. The result looks good for NYU-v2, but for KITTI dataset, it didn't give a close match with the paper. 

NYU-v2

`
abs_relative_difference     5.35                delta1_acc   97.38
`

KITTI
`
abs_relative_difference   12.28                delta1_acc  86.58
`

Wondering if the smaller datasets or the full datasets (commented out) in [`dataset_val.yaml` ](https://github.com/prs-eth/Marigold/blob/main/config/dataset/dataset_val.yaml) are used in the paper for validation? The paper mentioned "Eigen test split [ 14 ] made of 652 images" for validation on KITTI dataset, but I couldn't find the corresponding data split file. Would you mind sharing it?

Thank you very much for any help!

**Comment by markkua** [comment]
Hi, the full datasets are used for the paper evaluation. You can find the corresponding config files in the scripts [here](https://github.com/prs-eth/Marigold/tree/main/script/eval). As for KITTI dataset, [this data split](https://github.com/prs-eth/Marigold/blob/main/data_split/kitti/eigen_test_files_with_gt.txt) is the one you are looking for. There are some files with out GT, resulting in 652 valid samples at the end.
