### ISSUE TITLE
Is it possible to train the model by feeding it rgb images + 8-bit relative depth maps ?

### ISSUE THREAD

**Issue by YacineDeghaies** [prs-eth/Marigold#97]
I want to train this model on a new dataset, but before that, I want to ensure that the model is suitable for my manually made grayscale depth maps.

One example of my depth maps:

![shot_0002_dm_gt_s_0128](https://github.com/prs-eth/Marigold/assets/56239998/51d3aa75-59be-4852-8cf7-c311dae05257)

**Comment by nandometzger** [comment]
Hi there, thank you for the interest.

I would assume that it also works with your manual depth maps. There is a cheap sanitycheck to check the capabilities of the VAE. You can encode and decode your depth map, which should result in an reconstructed depthmap. Other then that, I think you should just try. Hint: you can resume training from the marigold checkpoint :)

**Comment by YacineDeghaies** [comment]
Thank you for your answer. I'm still trying with it.
Can you please clarify what do you mean by 

> You can encode and decode your depth map, which should result in an reconstructed depthmap.

Is this a code I need to write ?
