### ISSUE TITLE
Data cannot be read during training

### ISSUE THREAD

**Issue by dongyyyy** [prs-eth/Marigold#99]
I just used the vkitti dataset, RGB data path for autodl - TMP/Marigold - main/vkitti/vkitti tar/vkitti/RGB, The depth data path for autodl - TMP/Marigold - main/vkitti/vkitti tar/vkitti/the depth.When I run the training file, the parameter is set to: export BASE_DATA_DIR=vkitti.
dataset:
  train:
    name: vkitti
    prob_ls: [0.9, 0.1]
    disp_name: vkitti_train
    dir: vkitti.tar
    filenames: vkitti/vkitti.txt
    kitti_bm_crop: true
    valid_mask_crop: null
But there is still such a problem, I do not know what to do.
<img width="450" alt="problem1" src="https://github.com/user-attachments/assets/7c949358-99cb-4f18-9f4a-2351904b380a">
<img width="416" alt="problem2" src="https://github.com/user-attachments/assets/a7737b8f-5189-4572-9efe-dc9922de6f5e">

**Comment by markkua** [comment]
Hi. Something seems wrong with the file path correspondence. If you try it without tar, you might find the problem more easily.
